[package]
name = "smoltcp-nal"
version = "0.1.0"
authors = ["Ryan Summers <ryan.summers@vertigo-designs.com>"]
edition = "2018"
license = "MIT"
description = "embedded-nal implementation for smoltcp"
keywords = ["smoltcp", "embedded-nal", "tcp"]
categories = ["network-programming", "no-std"]
repository = "https://github.com/quartiq/smoltcp-nal.git"

[dependencies]
heapless = "0.7"
embedded-nal = "0.6"
critical-section = "0.2.4"

[dependencies.nanorand]
version = "0.6.1"
default-features = false
features = ["wyrand"]

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp"
branch = "master"
features = ["medium-ethernet", "socket-tcp", "socket-dhcpv4", "socket-udp", "rand-custom-impl", "defmt"]
default-features = false
